spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug